# Generated by Django 4.2 on 2023-04-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chore',
            old_name='user',
            new_name='assigned_to',
        ),
    ]
