# Generated by Django 4.2 on 2023-04-19 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_rename_user_chore_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='created',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='description',
        ),
        migrations.AlterField(
            model_name='chore',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
