# Generated by Django 4.2 on 2023-04-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_chore_assigned_to_remove_chore_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='son',
            old_name='assigned_to',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='son',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='son',
            name='created',
        ),
        migrations.RemoveField(
            model_name='son',
            name='description',
        ),
        migrations.RemoveField(
            model_name='son',
            name='title',
        ),
        migrations.AddField(
            model_name='son',
            name='account',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='son',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
