# Generated by Django 4.2 on 2023-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_assigned_to_son_name_remove_son_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
