# Generated by Django 4.2 on 2023-04-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chore_created_chore_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='base.son'),
        ),
    ]
