# Generated by Django 4.2 on 2023-04-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_chore_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chores', to='base.son'),
        ),
    ]
