# Generated by Django 4.2 on 2023-04-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_chore_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
