# Generated by Django 4.2 on 2023-04-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_chore_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='son',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
